### ISSUE TITLE
Which repo?

### ISSUE THREAD

**Issue by Ramblurr** [HinTak/seeed-voicecard#12]
thanks for maintaining this drivers, you're a saint!

Which repo should we use? The readme for this one points to https://github.com/HinTak/seeed-voicecard and the readme over there points to the original unmaintained repo.

It seems like this repo should be the one to use since you've merged in the latest mainline to the master branch?

**Comment by HinTak** [comment]
There is no difference between the two, the "-x" repo contains the most current branch of the fork. The default branch of the fork ties to the raspberrypi releases, so may not be the most current, as raspberrypi releases are somewhat behind mainstream Linux. Stay with the fork and switch branches as you change kernel.
