### ISSUE TITLE
about kernel  ： kernel 6.5.0-1005-raspi cannot be found

### ISSUE THREAD

**Issue by nicktao9** [HinTak/seeed-voicecard#27]
Error! Your kernel headers for kernel 6.5.0-1005-raspi cannot be found at /lib/modules/6.5.0-1005-raspi/build or /lib/modules/6.5.0-1005-raspi/source.

USE:
Linux ubuntu 6.5.0-1005-raspi #7-Ubuntu SMP PREEMPT_DYNAMIC Sun Oct  8 08:06:18 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
v6.1 and v6.5 do not work

**Comment by HinTak** [comment]
For ubuntu, you need to do `sudo apt-get install -y linux-headers-raspi` to get the kernel headers. This is part of the `install.sh` script. (Read it...)
