### ISSUE TITLE
I cant get it to work unless I use an older kernel version and then lxpanel seems to break

### ISSUE THREAD

**Issue by TheSwedishMaker** [HinTak/seeed-voicecard#8]
do you have any plans on updating this version of the driver? It seems Seeed themselves wont do any updates to their drivers, but no matter how I've tried - I cant get it to work properly on any version. The only time I got the drivers properly installed was either on the 2021 may version of Raspberry OS or by downgrading the kernel version but then the LXpanel drops and there's no visible menu bar.

**Comment by HinTak** [comment]
This was documented elsewhere: you can stop lxpanel from crashing if you uninstall `alsa-pulseaudio`, I think. Search here or upstream on closed issues about 'lxpanel'. 

As for older kernels, here my repo has always been organised by kernel versions. You just use the "vX.Y"branch, if your kernel is X.Y.Z.

**Comment by HinTak** [comment]
I am moving this issue over to the fork (which have older branches - the detached "-x" mirror only keeps the latest) - and you should just use the correct branch. I an closing this now.
